add_newline = false

format = """
$username$hostname$directory
$jobs$battery$cmd_duration$character"""

[username]
show_always = true
style_user = "#ebdbb2"
format = "[$user]($style)"

[hostname]
style = "#ebdbb2"
format = "[@](bold #fabd2f)[$hostname]($style)"

[directory]
style = "#ebdbb2"
format = " [· [$path]($style) で](bold #fabd2f) "

[jobs]
threshold = 0
style = "bold #fabd2f"
format = '[\[$number\]]($style) '

[[battery.display]]
threshold = 25
style = "bold #fb4934"

[[battery.display]]
threshold = 33
style = "bold #fabd2f"

[cmd_duration]
style = "bold #fabd2f"
format = '[\($duration\)]($style) '

[character]
success_symbol = ""
error_symbol = ""
vicmd_symbol = ""
format = "[コマンド](bold #ebdbb2) [❯](bold #fabd2f) "

