add_newline = false

format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[username]
show_always = true
style_user = "#ebdbb2"
format = "[$user]($style)[@](bold #fabd2f)"

[hostname]
style = "#ebdbb2"
ssh_only = false
format = "[$hostname [·](bold #fabd2f) ]($style)"

[directory]
style = "#ebdbb2"
read_only = "(read only)"
format = "[$path]($style) [で](bold #fabd2f) "

[[battery.display]]
threshold = 10
style = "bold #fb4934"

[[battery.display]]
threshold = 20
style = "bold #fabd2f"

[character]
success_symbol = "[コマンド](bold #ebdbb2)"
error_symbol = "[コマンド](bold #ebdbb2)"
vicmd_symbol = "[コマンド](bold #ebdbb2)"

